image: node:14.20.0

pipelines:
  branches:
    '{master,release/qa}':
      - step:
          name: "Initial"
          script:
            - echo "Default step" 
      - step:
          name: "Build and push images"
          trigger: manual
          caches:
            - node
          script:
            - npm install
            - npm install -g @angular/cli@11.2.11
            - ng build --prod
            - echo "ls" 
            - ls           
            - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
            - BRANCH_NAME=$(echo $BITBUCKET_BRANCH | sed "s/[^a-zA-Z0-9]/-/g")
            - TAG_NAME=$BRANCH_NAME.$(date +%Y%m%d.%H%M%S)
            - IMAGE_NAME=dronline/binah-sdk-web:$TAG_NAME
            - docker build -t $IMAGE_NAME .
            - docker push $IMAGE_NAME
          services:
            - docker